name: Flutter CI/CD - Firebase Distribution

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Descargar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Instalar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4' # ajusta seg√∫n tu versi√≥n

      # 3Ô∏è‚É£ Instalar dependencias
      - name: Get dependencies
        run: flutter pub get

      - name: Set version from GitHub run number
        run: |
          base_version=$(grep '^version:' pubspec.yaml | cut -d+ -f1 | awk '{print $2}')
          new_version="${base_version}+${{ github.run_number }}"
          sed -i "s/^version:.*/version: $new_version/" pubspec.yaml


          
      # 5Ô∏è‚É£ Compilar app Android

      - name: Build Android APK 
        run: flutter build apk --release    

      # 7Ô∏è‚É£ Subir Android a Firebase App Distribution
      - name: Upload Android to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Versi√≥n Android generada autom√°ticamente desde GitHub Actions üöÄ"

      # 8Ô∏è‚É£ Subir iOS a Firebase App Distribution (si aplica)
      - name: Upload iOS to Firebase App Distribution
        if: ${{ hashFiles('build/ios/ipa/*.ipa') != '' }}
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/ios/ipa/*.ipa
          releaseNotes: "Versi√≥n iOS generada autom√°ticamente desde GitHub Actions üçéüöÄ"
      # 9Ô∏è‚É£ Notificar finalizaci√≥n
      - name: Notify completion
        run: echo "‚úÖ Distribuci√≥n a Firebase App Distribution completada." 